name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  labels:
    description: 'Provide a comma separated list of labels passed to the PR for the version bump.'
    required: true
    default: 'patch'
  path:
    description: 'Path of package.json'
    default: "./"
  node-version-file:
    description: 'File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions.'
    default: "./nvmrc"

# Define your outputs here.
outputs:
  version:
    description: "Version of package"

runs:
  using: node16
  main: dist/index.js
